[tool.poetry]
name = "ami-deprecation-tool"
version = "0.1.0"
description = ""
authors = ["Ryan Hill <ryan.hill@canonical.com>"]
readme = "README.rst"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
