name: testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tox:
    runs-on: self-hosted
    strategy:
      matrix:
        python: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install tox and any other packages
        run: |
          pip3 install tox
      - uses: actions/checkout@v4
      - name: Run tox
        run: tox
  snap:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: snapcore/action-build@v1
